# Generated by Django 2.1.5 on 2020-06-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spam',
            fields=[
                ('spam_id', models.IntegerField(primary_key=True, serialize=False)),
                ('spam_mobno', models.IntegerField()),
                ('spam_count', models.IntegerField()),
            ],
            options={
                'db_table': 'spam',
                'managed': True,
            },
        ),
    ]
