# Generated by Django 2.1.5 on 2020-06-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserContacts',
            fields=[
                ('uc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('contact_regid', models.IntegerField()),
                ('uc_fname', models.CharField(max_length=255)),
                ('uc_lname', models.CharField(max_length=255)),
                ('uc_mobno', models.IntegerField()),
            ],
            options={
                'db_table': 'usercontacts',
                'managed': True,
            },
        ),
    ]
