# Generated by Django 2.1.5 on 2020-06-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontacts',
            old_name='uc_fname',
            new_name='uc_name',
        ),
        migrations.RemoveField(
            model_name='usercontacts',
            name='uc_lname',
        ),
    ]
